# Generated by Django 5.1.6 on 2025-04-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'General Physician'), ('cardiology', 'Cardiologist'), ('dermatology', 'Dermatologist'), ('neurology', 'Neurologist'), ('pediatrics', 'Pediatrician')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]
